apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jxui
spec:
  rules:
  - host: {{ .Values.previewname }}.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: sso-preview-jxui
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.previewname }}.{{ .Values.domain }}
    secretName: "tls-cbjx-slavegrove-play-jxaas-live-p"